# Copyright 2021 Google Inc. All Rights Reserved.
#
# Distributed under MIT license.
# See file LICENSE for detail or copy at https://opensource.org/licenses/MIT

name: Build

on: [push]

jobs:
  ubuntu_build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:

          - name: Linux
            build_system: bazel
            bazel_project: .
            os: ubuntu-18.04

          - name: MacOS
            build_system: bazel
            bazel_project: .
            os: macos-10.15

          - name: Windows
            build_system: make
            os: windows-2019

    env:
      CC: ${{ matrix.c_compiler || 'gcc' }}
      CXX: ${{ matrix.cxx_compiler || 'gcc' }}

    steps:
    - name: Install extra deps @ Ubuntu
      if: ${{ runner.os == 'Linux' }}
      # Already installed: bazel, clang{10-12}, cmake, gcc{9,10}, java{8,11}, maven, python{2.7,3.5-3.9}
      run: |
        EXTRA_PACKAGES="${{ matrix.extra_apt_pkgs || '' }}"
        sudo apt update
        sudo apt install -y ${EXTRA_PACKAGES}

    - name: Checkout the source
      uses: actions/checkout@v2
      with:
        submodules: false
        fetch-depth: 1

    - name: Build with Bazel
      if: ${{ matrix.build_system == 'bazel' }}
      run: |
        cd ${GITHUB_WORKSPACE}/${{ matrix.bazel_project }}
        bazel build -c opt ...:all

    - name: Build with Make
      if: ${{ matrix.build_system == 'make' }}
      run: |
        make brotli

    - name: Create brotli archive on Mac / Linux
      if: ${{ runner.os != 'Windows' }}
      run: zip brotli.zip bazel-bin/brotli

    - name: Upload artifacts on Mac / Linux
      if: ${{ runner.os != 'Windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-build.zip
        path: brotli.zip

    - name: Upload artifacts on Windows
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-build.zip
        path: bin
